# This file works with the "humao.rest-client" extension for VS Code

@host = http://localhost:8080/api/v1
#@dumpster_id = c37246d2-3088-45eb-af40-87dfdd6bf314
@dumpster_id = 4dcd70bb-4d32-464f-bda0-fd28eb5fe403
@user_id = c3c0687f-0c03-4f48-a664-4bc616abffe6

###

GET {{host}}/
###

POST {{host}}/
###

GET {{host}}/dumpsters
###

GET {{host}}/dumpster/{{dumpster_id}}
###

GET {{host}}/dumpster/{{dumpster_id}}/token
###

GET {{host}}/dumpster/{{dumpster_id}}/availability
###

POST {{host}}/dumpster/{{dumpster_id}}/availability
Content-Type: application/json

{
    "available": true
}
###

POST {{host}}/dumpster/{{dumpster_id}}/dump
Content-Type: application/json

{
    "user_id": "{{user_id}}",
    "dump_type": "unsorted"
}
###

POST {{host}}/dumpster/{{dumpster_id}}/weight
Content-Type: application/json

{
    "weight": 0
}
###
